/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Avatar: typeof import('antd')['Avatar']
  const Button: typeof import('antd')['Button']
  const Checkbox: typeof import('antd')['Checkbox']
  const ConfigProvider: typeof import('antd')['ConfigProvider']
  const Dropdown: typeof import('antd')['Dropdown']
  const Form: typeof import('antd')['Form']
  const Group: typeof import('antd')['Group']
  const Input: typeof import('antd')['Input']
  const LoadingOutlined: typeof import('@ant-design/icons')['LoadingOutlined']
  const Message: typeof import('antd')['Message']
  const Modal: typeof import('antd')['Modal']
  const Radio: typeof import('antd')['Radio']
  const Select: typeof import('antd')['Select']
  const Space: typeof import('antd')['Space']
  const Spin: typeof import('antd')['Spin']
  const Table: typeof import('antd')['Table']
  const Tooltip: typeof import('antd')['Tooltip']
}
