/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Avatar: typeof import('antd')['Avatar']
  const Button: typeof import('antd')['Button']
  const Checkbox: typeof import('antd')['Checkbox']
  const Collapse: typeof import('antd')['Collapse']
  const ConfigProvider: typeof import('antd')['ConfigProvider']
  const DatePicker: typeof import('antd')['DatePicker']
  const Dropdown: typeof import('antd')['Dropdown']
  const FaRegUser: typeof import('react-icons/fa6')['FaRegUser']
  const Flex: typeof import('antd')['Flex']
  const FloatButton: typeof import('antd')['FloatButton']
  const Form: typeof import('antd')['Form']
  const Group: typeof import('antd')['Group']
  const Input: typeof import('antd')['Input']
  const IoIosAdd: typeof import('react-icons/io')['IoIosAdd']
  const IoIosArrowForward: typeof import('react-icons/io')['IoIosArrowForward']
  const IoIosWoman: typeof import('react-icons/io')['IoIosWoman']
  const IoMdInformationCircle: typeof import('react-icons/io')['IoMdInformationCircle']
  const LoadingOutlined: typeof import('@ant-design/icons')['LoadingOutlined']
  const LuBaby: typeof import('react-icons/lu')['LuBaby']
  const MdModeEdit: typeof import('react-icons/md')['MdModeEdit']
  const Message: typeof import('antd')['Message']
  const Modal: typeof import('antd')['Modal']
  const Progress: typeof import('antd')['Progress']
  const Radio: typeof import('antd')['Radio']
  const Select: typeof import('antd')['Select']
  const Space: typeof import('antd')['Space']
  const Spin: typeof import('antd')['Spin']
  const Steps: typeof import('antd')['Steps']
  const Table: typeof import('antd')['Table']
  const Tooltip: typeof import('antd')['Tooltip']
  const message: typeof import('antd')['message']
  const theme: typeof import('antd')['theme']
}
